name: Pytorch ML Github Actions Depoloyment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda config --set restore_free_channel true
        conda env update -n pytorch_env --file conda.yaml
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Model Training
      run: |
        python3 main.py
    - name: Get IP
        echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
